spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost:18080/~/smutaxi
    username: sa
    password:
    driver-class-name: org.h2.Driver

  kafka:
    consumer:
      group-id: consumer-id
      bootstrap-servers: localhost:9092

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: oddman0w0@gmail.com
    password: rlrgstbdizehglru
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

security:
  jwt:
    token:
      secret-key: MySuperSecretKey123!MySuperSecretKey123!MySuperSecretKey123!
      expire-length: 3600000
fcm:
  key:
    path: gjgs-fcm.json


matching:
  pool-size: 500

server:
  baseUrl: http://192.168.219.110:8080
  upload:
    directory: C:\spoot-taxi-profile-imgs
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace #??? ?? 2.x, hibernate5
  org.springframework.messaging.simp: DEBUG #stomp 로그때문에 넣음
  org.springframework.security: debug #security 로그
# org.hibernate.orm.jdbc.bind: trace #??? ?? 3.x, hibernate6